### ISSUE TITLE
proprietary license identifier

### ISSUE THREAD

**Issue by dsbaars** [puppet-community/metadata-json-lint#12]
The spdx license list only contains open-source licenses. Other json configs, like composer.json and package.json allow the "proprietary" license identifier for closed-source projects. I hope this can be allowed here as well.

https://getcomposer.org/doc/04-schema.md#license

**Comment by nibalizer** [comment]
Interesting. @ryanycoleman reccomended the spdx library because it is what the forge uses for validation. We could add code to try validating against spdx, the try validating against proprietary, then fail.

**Comment by domcleal** [comment]
I guess the Forge isn't ever going to accept 'proprietary' as a licence string, since they wouldn't be able to redistribute the code, but @nibalizer's suggestion sounds like a good idea - allow it as a special string.

**Comment by dsbaars** [comment]
I really would like to be able to validate my (or my companies) proprietary puppet-modules `metadata.json` without the need for "--no-strict-license", not all modules go the the forge ;)

**Comment by jantman** [comment]
I agree... my company uses "Proprietary" to identify modules which we haven't open sourced (this is a management approval process for us). I'd still like to be able to keep these modules release-ready...

**Comment by igalic** [comment]
:+1:

**Comment by tuxinaut** [comment]
:+1:

**Comment by igalic** [comment]
anyone care to provide a patch here ;)

**Comment by dsbaars** [comment]
Sure :)

**Comment by dsbaars** [comment]
My pull request is merged (thanks!) and solves the issue so i'll close it.
